package bak.websiteanalysis;

/**
 * AnalysisOutput is responsible for outputting the data parsed from each
 * file containing html tags. Three files will be created: JSON (.json),
 * Microsoft Excel (.xlsx), and a text file (.txt). These files will be stored
 * in a directory called "output" which can be found in the root directory of
 * the website. This directory will most likely not exist prior to running
 * this program, so it must be created programmatically.
 * 
 * @author Brian Klarman	b.klarman@gmail.com
 * 
 * @see jsonExport()
 * @see textExport()
 * @see excelExport()
 *
 */
public class AnalysisOutput {
	/**
	 * The JSON file should describe each page and resource in the site:
	 * <ul>
	 * <li>One entry per page detailing:</li>
	 * 		<ul>
	 * 		<li>Number of local images</li>
	 * 		<li>Number of external images</li>
	 * 		<li>Number of scripts referenced</li>
	 * 		<li>Number of stylesheets utilized</li>
	 * 		<li>Listing of images</li>
	 * 		<li>Listing of scripts</li>
	 * 		<li>Listing of stylesheets</li>
	 * 		<li>Number of intra-page links</li>
	 * 		<li>Number of inter-site links</li>
	 * 		<li>Number of external links</li>
	 * 		</ul>
	 * <li>One entry per image detailing:</li>
	 * 		<ul>
	 * 		<li>Number of pages on which it is displayed</li>
	 * 		<li>Listing of pages on which it is displayed</li>
	 * 		</ul>
	 * <li>One entry per archive file detailing:</li>
	 * 		<ul>
	 * 		<li>File size</li>
	 * 		<li>Path to resource (relative to local site root)</li>
	 * 		</ul>
	 * <li>One entry per video file detailing:</li>
	 * 		<ul>
	 * 		<li>File size</li>
	 * 		<li>Path to resource (relative to local site root)</li>
	 * 		</ul>
	 * <li>One entry per audio file detailing:</li>
	 * 		<ul>
	 * 		<li>File size</li>
	 * 		<li>Path to resource (relative to local site root)</li>
	 * 		</ul>
	 * <li>One entry per non-categorized file detailing:</li>
	 * 		<ul>
	 * 		<li>File size</li>
	 * 		<li>Path to resource (relative to local site root)</li>
	 * 		</ul>
	 * </ul>
	 * 
	 * @author Brian Klarman	b.klarman@gmail.com
	 */
	public void jsonExport() {
		
	}
	
	/**
	 * The text file must output all traversed local pages sorted
	 * lexicographically by directory-starting with the site root. Each line
	 * should take the form:<p> size	page<p>
	 * where size is the cumulative size of all images (in MiB to 2 decimal
	 * places) on the page, and page is the local file path.
	 * <p>
	 * The last line of the file shall contain the sum of all page sizes.
	 * <p>
	 * This format mirrors what is generated by the Linux du command.
	 */
	public void textExport() {
		
	}
	
	/**
	 * The Excel document will consist of a single Excel workbook with a single
	 * sheet named 'summary'. The document will take the form:<p>
	 * Header row: Page, # Images, #CSS, Scripts, #Links (Intra-page),
	 * #Links (Inter-site), #Links (External).
	 * <p>
	 * The first row consists of headings. Each reaming row (one per internal)
	 * pages lists the indicated counts.
	 */
	public void excelExport() {
		
	}
	
	/**
	 * Creates the header row for the Excel file that is created.
	 * 
	 * @see excelExport()
	 */
	public void createExcelHeader() {
		
	}
}
