/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bak.websiteanalysis;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAUsageMessage() {
        App classUnderTest = new App();
        assertNotNull("app should have a usage message", classUnderTest.getUsageMessage());
    }
}
